# Generated by Django 5.1.6 on 2025-03-28 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Missed Word'), ('2', 'Ordering'), ('3', 'Pronunciation'), ('4', 'Audition')], max_length=2)),
                ('question', models.TextField()),
                ('sentence_without_a_word', models.TextField(blank=True)),
                ('variants', models.JSONField(blank=True, default=list)),
                ('missed_word', models.TextField(blank=True)),
                ('sentence_for_ordering', models.TextField(blank=True)),
                ('mp3', models.FileField(blank=True, upload_to='mp3/')),
                ('text_to_speech', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(blank=True, default=1)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='courses.topic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
