# Generated by Django 5.1.6 on 2025-03-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
